# Generated by Django 5.2.15 on 2026-06-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField(unique=True)),
                ('solar_system_id', models.IntegerField()),
                ('solar_system_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('attacker_score', models.FloatField(default=0)),
                ('defender_score', models.FloatField(default=0)),
                ('start_time', models.DateTimeField()),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SovConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook_url', models.URLField(blank=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SovOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sov_owner', to='eveonline.eveallianceinfo')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter')),
            ],
            options={
                'permissions': (('view_sov', 'Can view SOV Monitor'), ('manage_sov', 'Can manage SOV Monitor alliances')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SovSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_system_id', models.IntegerField(unique=True)),
                ('solar_system_name', models.CharField(blank=True, max_length=100)),
                ('constellation_name', models.CharField(blank=True, max_length=100)),
                ('region_name', models.CharField(blank=True, max_length=100)),
                ('adm', models.FloatField(default=0)),
                ('has_ihub', models.BooleanField(default=False)),
                ('has_tcu', models.BooleanField(default=False)),
                ('vulnerable_start', models.DateTimeField(blank=True, null=True)),
                ('vulnerable_end', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='aa_sov_monitor.sovowner')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SovUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='aa_sov_monitor.sovsystem')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('system', 'type_id')},
            },
        ),
    ]
