# Generated by Django 5.2.15 on 2026-06-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0002_sovupgrade_power_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovHubResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_available', models.IntegerField(default=0)),
                ('power_allocated', models.IntegerField(default=0)),
                ('workforce_available', models.IntegerField(default=0)),
                ('workforce_allocated', models.IntegerField(default=0)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_resource', to='aa_sov_monitor.sovsystem')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SovHubReagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('burning_per_hour', models.FloatField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_reagents', to='aa_sov_monitor.sovsystem')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('system', 'type_id')},
            },
        ),
    ]
