# Generated by Django 5.2.15 on 2026-06-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0003_sovhubresource_sovhubreagent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sovowner',
            options={'default_permissions': (), 'permissions': (('view_sov', 'Can view SOV Monitor'), ('manage_sov', 'Can manage SOV Monitor alliances'), ('view_manager', 'Can view SOV Monitor Manager tab'))},
        ),
    ]
