# Generated by Django 5.2.15 on 2026-06-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0004_alter_sovowner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sovsystem',
            name='industrial_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sovsystem',
            name='military_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sovsystem',
            name='strategic_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm', models.FloatField()),
                ('industrial_level', models.IntegerField(default=0)),
                ('military_level', models.IntegerField(default=0)),
                ('strategic_level', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_history', to='aa_sov_monitor.sovsystem')),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['system', 'recorded_at'], name='aa_sov_moni_system__16f5aa_idx')],
            },
        ),
    ]
