# Generated by Django 5.2.15 on 2026-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0005_sovsystem_industrial_level_sovsystem_military_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sovconfiguration',
            name='webhook_adm',
            field=models.URLField(blank=True, verbose_name='Webhook: ADM-Alerts'),
        ),
        migrations.AddField(
            model_name='sovconfiguration',
            name='webhook_module',
            field=models.URLField(blank=True, verbose_name='Webhook: Modul-Alerts'),
        ),
        migrations.AddField(
            model_name='sovconfiguration',
            name='webhook_reagent',
            field=models.URLField(blank=True, verbose_name='Webhook: Reagent-Alerts'),
        ),
        migrations.AddField(
            model_name='sovsystem',
            name='adm_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sovsystem',
            name='reagent_alert_level',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sovconfiguration',
            name='discord_webhook_url',
            field=models.URLField(blank=True, verbose_name='Webhook: Campaigns'),
        ),
    ]
