# Generated by Django 5.2.15 on 2026-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0006_sovconfiguration_webhook_adm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_sov', 'Can view SOV Monitor'), ('manage_sov', 'Can manage SOV Monitor alliances'), ('view_manager', 'Can view SOV Monitor Manager tab')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='sovowner',
            options={'default_permissions': ()},
        ),
    ]
