# Generated by Django 5.2.15 on 2026-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_sov_monitor', '0007_general_model_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sovconfiguration',
            name='webhook_adm',
            field=models.URLField(blank=True, verbose_name='Webhook: ADM Alerts'),
        ),
        migrations.AlterField(
            model_name='sovconfiguration',
            name='webhook_module',
            field=models.URLField(blank=True, verbose_name='Webhook: Module Alerts'),
        ),
        migrations.AlterField(
            model_name='sovconfiguration',
            name='webhook_reagent',
            field=models.URLField(blank=True, verbose_name='Webhook: Reagent Alerts'),
        ),
    ]
